### ISSUE TITLE
How does the static modification work when the initial generation of fragments and peptides?

### ISSUE THREAD

**Issue by Wonyeop** [lazear/sage#126]
Hello Michael.

I performed two searches with no labeled and TMT labeled data for the same fasta format database.
Even though I ran only Sage without any other job on the same server, it did not work due to insufficient memory to search TMT labeled data.

There were no additional options except adding TMT static modifications(K and N-terminal) and the tmt quant option.

What causes additional memory consumption during the initial generation of fragments and peptides step?
Did I do something wrong with configuration settings?

**Comment by lazear** [comment]
Can you paste your config file just to check? How many proteins are in the fasta? How much RAM do you have? A typical non-redundant human digest with TMT mods shouldn't use much memory.

Static modifications shouldn't require additional memory, but it's possible that you ran out of memory during peptide generation due to some overhead of actually applying modifications.

**Comment by Wonyeop** [comment]
The server where the phenomenon was confirmed had 64GB memory. It seems that there was not enough memory to analyze about 1.4 million tryptic peptides.

If applying modifications was conducted during peptide generation step, i can understand the lack of memory.

Thank you for your response :)

**Comment by lazear** [comment]
64 GB of RAM should be more than sufficient for that. Without more details (the configuration file, FASTA, maybe the mzML) I cannot help you though!
