### ISSUE TITLE
Quantitation

### ISSUE THREAD

**Issue by lgatto** [lazear/sage#45]
Could you clarify whether sage does TMT MS2 quantitation (none in our result files)? Re-reading the README file, it looks like it's only MS3. 

Thank you in advance.

**Comment by lazear** [comment]
There is support for MS2 quantitation in the codebase, but it's not enabled as a CLI flag yet. Let me push out a release that enables this.

I haven't tested MS2 quant, but I have extensively validated the MS3 quant against Proteome Discoverer (across 100s of files). MS2 quant uses the same quantitation code, so it should be fine, but let me know if there are any issues.

**Comment by lazear** [comment]
OK - v0.8.1 has a configuration flag `quant.tmt_level` that can be set to 2 (defaults to 3). Sage is currently also pre-processing MS2 spectra for search (`fragment_min_mz`, `deisotope` options), so make sure to set these to reasonable values (126, false) so that MS2 quantitation can proceed smoothly

**Comment by lgatto** [comment]
Thank you! Will test and report back here.

**Comment by lgatto** [comment]
All working as expected here. We haven't been able to compare the quantitation data against other software yet, but the distributions look as expected.

**Comment by lazear** [comment]
Great! I will close the issue for now, please re-open if anything looks wonky!
