### ISSUE TITLE
Problem analysing tims-tof data

### ISSUE THREAD

**Issue by tomthun** [lazear/sage#72]
Hello,

I currently wanted to test sage and compare it to other Software tools but cannot get it to produce results. [Error.txt](https://github.com/lazear/sage/files/11565398/error.txt) is the detailed output i get when running sage. As input I use tims-tof (.d)-converted .mzML files which i thought might be the issue. Hence tried different methods of generating these:

1.  I used the guide as described at the bottom of this [page](https://fragpipe.nesvilab.org/docs/tutorial_convert.html).
2.  I first converted the .d folders to .mgf with the alphatims package and then again used msconvert-GUI but with no changes to the default parameters (in contrast to the [guide](https://fragpipe.nesvilab.org/docs/tutorial_convert.html)). This yielded a much smaller mzml file (500 mb vs 5gb for the "same" mzML files in 1.) so there are definitly some changes.

This is the fasta i use: [NIST 8671_2021-11-22.txt](https://github.com/lazear/sage/files/11565422/NIST.8671_2021-11-22.txt)
Could it be that i just have to few proteins in the fasta? Otherwise have not changed any of the default parameters of the  
[results.json](https://github.com/lazear/sage/files/11565591/json.txt) except the path variables of fasta and output paths. 

I hope you can help me get more meaningful results and thank you in advance!!

Tom

**Comment by lazear** [comment]
Hi Tom,

Thanks for trying Sage - especially with tims data; that's uncharted territory! The error messages suggest that no confident PSMs were found (despite spectra being successfully read), hence failures to perform RT alignment, modeling, and discriminant analysis. This is likely due to too few proteins in the fasta file. I would try with a full sized proteome fasta file.

Alternatively, there should still be PSMs present in the output file, just without any confidence estimates.

**Comment by tomthun** [comment]
Hi,

I get PSMs in the output file, but just very few of them and with no confidence estimates.
I am using methods of unspecific cleavage of the proteins, is there anyway to include that in the results.json so that we might get more peptide mappings? Does SAGE work at all with unspecific digestion of proteins?

**Comment by lazear** [comment]
So is this resolved?
