### ISSUE TITLE
LFQ output is empty

### ISSUE THREAD

**Issue by tomthun** [lazear/sage#74]
Hey Michael,

I tried running a bigger Dataset with LFQ and wondered why the lfq.tsv table is empty.
The columns header gets generated but all rows are empty. 
Do I need to specify something else in the config.json than setting lfq = True?  

Best,
Thomas

**Comment by lazear** [comment]
Can you please share the results.json file and log information (try also running sage with tracing enabled command `SAGE_LOG=trace ./sage`)? Is it also possible to share an mzML?

**Comment by tomthun** [comment]
Hey, here is the [results.json](https://github.com/lazear/sage/files/11665478/results.txt). I still have to think about a way to provide a mzml file.  

During a discussion with a college we came to the conclusion that it may be a problem with the conversion of .d to mzml.
As i have described in #72 i used alphatims to convert to mgf and msconvert to convert to mzml and hence there might be some information loss of ms1 spectra.

**Comment by tomthun** [comment]
I am currently creating the log files. Do you have a private email so that i can send you the link to the mzml? 

Regarding PSMs and peptides: they are confidently ided, i get 2401 decoys of 822772 peptides when filtering for PSM and peptide qvalue < 0.01 for both

**Comment by lazear** [comment]
My email can be found in this file: https://github.com/lazear/sage/blob/master/crates/sage/Cargo.toml

The tracing part needs to go before the actual command line invocation of sage, not in the JSON file: `SAGE_LOG=trace ./sage config.json -f human.fasta`

**Comment by tomthun** [comment]
Does tracing work with windows? I wrote you an email with the link to the data! :)

**Comment by lazear** [comment]
Thanks Thomas, I got the data and will ping you when I've had a change to investigate.

For windows you'll need to change the syntax depending on whether you're using powershell or something else. Basically just need to set an environment variable "SAGE_LOG=trace"

**Comment by lazear** [comment]
(There was an issue with the mzML file that was communicated to Thomas via email, closing for no-response)

Feel free to re-open if there is an issue with other mzMLs

**Comment by tomthun** [comment]
Hey, sorry for the delayed answer but i'd like to reopen this issue again and generally ask how you would do conversion (i currently use msconvert) for different types of data (.raw or .d). When i try to convert timsTof data in any way Sage seems to not pick up the MS1 spectra / cannot do LFQ. Do you have any general recommendations for conversions?

**Comment by jspaezp** [comment]
Helo there! 
at this time we have gotten the best results using this guy to convert the .d files to .mzml: https://github.com/mafreitas/tdf2mzml

But I think the underlying issue is that depending on the conversion tool, the way that collapsing all the 'scans' in a 'frame' (IMS elution) into a single scan can change dramatically. Tools that just 'collapse' the IMS dimension tend to give 'pseudo-centroid' data that might screw up with tools that match peaks by 'closest match' instead of integrating the matching area. On the other hand `tdf2mzml` seems to do some 'centroiding' that collapses the IMS features into real centroided peaks.

It is worth noting that I am aware that with some arguments `msconvert` does not collapse the IMS dimension, leading to every 'frame' being recorded as MANY `scans` with the ramping mobility values.

I know there was a mention of an intermediate conversion to .mgf ... and I can see that some tools/argument combinations might just remove MS1 data to support tools that do not expect ms1 scans in there.

header of an ms1 spectrum generated with tfd2mzml:
```xml
        <spectrum index="0" defaultArrayLength="24291" id="index=1">
          <cvParam cvRef="PSI-MS" accession="MS:1000511" name="ms level" value="1"/>
          <cvParam cvRef="PSI-MS" accession="MS:1000285" name="total ion current" value="19601770.0"/>
          <cvParam cvRef="PSI-MS" accession="MS:1000505" name="base peak intensity" value="4691.0" unitCvRef="PSI-MS" unitAccession="MS:1000131" unitName="number of detector counts"/>
          <cvParam cvRef="PSI-MS" accession="MS:1000504" name="base peak m/z" value="325.2882862039353" unitCvRef="PSI-MS" unitAccession="MS:1000040" unitName="m/z"/>
          <cvParam cvRef="PSI-MS" accession="MS:1000130" name="positive scan" value=""/>
          <cvParam cvRef="PSI-MS" accession="MS:1000127" name="centroid spectrum" value=""/>
          <cvParam cvRef="PSI-MS" accession="MS:1000579" name="MS1 spectrum" value=""/>
          <scanList count="1">
            <cvParam cvRef="PSI-MS" accession="MS:1000795" name="no combination" value=""/>
            <scan>
              <cvParam cvRef="PSI-MS" accession="MS:1000016" name="scan start time" value="0.0079112" unitCvRef="PSI-MS" unitAccession="UO:0000031" unitName="minute"/>
              <scanWindowList count="1">
                <scanWindow>
                  <cvParam cvRef="PSI-MS" accession="MS:1000501" name="scan window lower limit" value="100.000000" unitCvRef="PSI-MS" unitAccession="MS:1000040" unitName="m/z"/>
                  <cvParam cvRef="PSI-MS" accession="MS:1000500" name="scan window upper limit" value="1600.000000" unitCvRef="PSI-MS" unitAccession="MS:1000040" unitName="m/z"/>
                </scanWindow>
              </scanWindowList>
            </scan>
          </scanList>
```

LMK what you think (I will try to find some public hela dad dataset to use as an example)

**Comment by treitpeter** [comment]
Hi Michael, 
So is there a gold-standard to run .d folders since the TIMS-rust update? I add the .d files directly as mzml paths - but I'm getting empty lfq.tsv files, despite having lfq = true.  
Is it still necessary to convert to mzml, and if yes, what software / settings should we use to convert so that we don't lose the MS1 information?

**Comment by sme229** [comment]
Hi @lazear 
I'm having the same issue and my lfq.tsv file only contains headers. I started with .raw files and converted them to mzml using ThermoRawFileParser. Do you think it's a problem with how the files were converted as well?

**Comment by jspaezp** [comment]
> Hi @lazear @jspaezp 
> I'm having the same issue and my lfq.tsv file only contains headers. I started with .raw files and converted them to mzml using ThermoRawFileParser. Do you think it's a problem with how the files were converted as well? 

@sme229 

Would you mind uploading an example of the files ?

**Comment by sme229** [comment]
Hi @jspaezp 

[results.json](https://github.com/user-attachments/files/17357224/results.json)

The mzML file is too big to attach here, would it be possible to send it to you via email please?

**Comment by lazear** [comment]
@sme229 
Config file seems OK (but maybe try increasing the tolerance for LFQ)? In general, if there is an empty lfq.tsv file, it should be from one of two causes: a) no peptides were detected at 1% FDR or b) no centroided MS1 scans are present in the mzML.

If you want to share one of the files, my email can be found in this file: https://github.com/lazear/sage/blob/master/crates/sage/Cargo.toml

@treitpeter are you running a version you have compiled yourself? There are some improvements to the timsrust module since the latest 14.7 release that I need to get around to releasing :)

**Comment by sme229** [comment]
Thanks @lazear I just sent you one of my mzML files

**Comment by treitpeter** [comment]
@lazear I am running with version D:\sage-v0.14.7-x86_64-pc-windows-msvc\sage-v0.14.7-x86_64-pc-windows-msvc\sage.exe, passing the .d files directly as "mzml_path". I am happy to test anything new if you have something. I can send the .d files as well if you wish, they are PASEF DDA and DIA files. We also have further synchropasef files. @sme229 How did you convert your files to mzml? what happens with the IM dimension?

**Comment by jspaezp** [comment]
Just to be clear there are 2 issues here ...

1. @sme229 we are not sure if the conversion from thermo raw to mzml is generating MS1 spectra or whether no quant yields FDR < 0.01. 
2. @treitpeter has no lfq in bruker data being searched natively. (for the record, I have used in the past https://github.com/mafreitas/tdf2mzml for bruker data, which flattens the mobility dimension on every frame ... which kind of works for dia pasef and dda pasef, i really do not believe it will work in any diagonal/slice pasef variant). 
    - I am looking into the feasibility of adding native LFQ for bruker data in sage but I cannot promise anything RN ... In theory it is easy to get 'something' that 'works' but I do not believe that most simple approaches will be good in terms of quant accuracy/precision/s-n ratio since sage RN does not have a notion of a continuous dimension in the mobility space (which I believe leads to very noisy spectra bc the noise of all the mobility dimension is added but the signal is only present in a subset of the scans in the frame).
    - Time allowing I will keep you posted on how that progress goes.

**Comment by sme229** [comment]
Hi @lazear @treitpeter @jspaezp 

I've used wrong parameters for my DIA data, that's why the lfq.tsv was empty.
@treitpeter I used ThermoRawFileParser https://github.com/compomics/ThermoRawFileParser with default settings to convert .raw to mzML
Thanks so much for your help everyone.
