### ISSUE TITLE
Making spectral library by searching GPF-DIA files with Sage and other questions

### ISSUE THREAD

**Issue by k-p4** [lazear/sage#96]
Hi @lazear , 

I was hoping to recreate Fragpipe's [DIA SpecLib Quant workflow](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10338508/) but with Sage and DIA-NN. The idea would be to run 6 X Gas Phase Fractionation injections through Sage by setting `wide_window` then building a DIA-NN compatible speclib from results. A couple of questions here are:

- Does Sage perform better with any particular acquisition window (4m/z, 8m/z, 24 m/z etc.)
- Is MS-X acquisition supported?
- Any recommendations for building a spectral library with Skyline, Easypqp or other apps?

Thank you,
Karl

**Comment by lazear** [comment]
Hi Karl,

- Sage should work with any of the acquisition windows... not sure if there is a "best", as I haven't extensively tested different m/z windows. Maybe check out one of the GPF papers and run the files through Sage?  I would love to know the results!
- MS-X acquisition isn't supported (yet). If you're willing to share a mzML or a PRIDE project containing MS-X data, I can take a look at how it's encoded. At the moment, Sage supports multiple precursors internally (for handling, i.e. SPS data), but only considers the first encoded precursor for searching. I imagine MS-X is encoded as a list of precursors in an mzML so should be feasible...
- I haven't used easypqp yet, but that's what FragPipe is using. It should be possible to tweak Sage outputs into whatever format easypqp is expecting from FragPipe. If you go this route, I would appreciate any knowledge you can share.
[Talus Bio has kindly open sourced their Sage to .dlib converter](https://github.com/TalusBio/petasus/blob/main/petasus/masses.py), but then I think you need to import into Skyline and convert to blib? I had some issues with this step. 
I previously asked the Skyline team to add support for importing Sage results directly (since FragPipe, MQ, PD, etc are supported...) but they didn't seem [terribly interested](https://skyline.ms/announcements/home/support/thread.view?rowId=61119) (I will not be supporting any XML based formats). Perhaps you can add your voice?

**Comment by k-p4** [comment]
Thanks so much for the directions and suggestions! 

I will test them out with some data I have generated, and some PRIDE projects as well and get back to you.
